kind: pipeline
type: docker
name: publish

steps:
  
  # - name: restore-cache
    # image: appleboy/drone-sftp-cache
    # settings:
      # server: ftp.lsd.info
      # port: 2222
      # username: sftp
      # password: 123456
      # path: /cache
      # ignore_branch: true
      # restore: true
      # mount:
        # - node_modules
        
  - name: restore-cache
    image: drillster/drone-volume-cache
    privileged: true
    settings:
      restore: true
      mount:              #需要缓存的文件夹
        - node_modules
      ignore_branch: true #分支名称不参与缓存文件名（哈希）的生成
    volumes:
      - name: cache  # The Volume's name
        path: /cache # The path in the container 把宿主机缓存目录挂载到容器的此路径

  - name: install
    image: node:alpine
    commands:
      - npm install -g cnpm --registry https://registry.npm.taobao.org
      - cnpm i
    when:
      event: [push]
    depends_on:
      - clone
      - restore-cache


  # - name: rebuild-cache
    # image: appleboy/drone-sftp-cache
    # settings:
      # server: sftp
      # port: 2222
      # username: sftp
      # password: 123456
      # path: /cache
      # ignore_branch: true
      # rebuild: true
      # mount:
        # - node_modules
    # when:
      # event: [push]
    # depends_on:
      # - install
      
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    privileged: true
    settings:
      rebuild: true
      mount:              #需要缓存的文件夹
        - node_modules
      ignore_branch: true #分支名称不参与缓存文件名（哈希）的生成
    volumes:
      - name: cache  # The Volume's name
        path: /cache # The path in the container 把宿主机缓存目录挂载到容器的此路径
    depends_on:
      - install

  - name: build
    image: node:alpine
    commands:
      - npm run build
    depends_on:
      - install

  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    failure: ignore  #代码质量分析成功与否，不影响其他管道执行
    settings:
      sonar_host: http://192.168.11.101:9000
      sonar_token: 9bc80cee1e0c5c8e594ed471e865eaa4ffcbb131
    when:
      event: [push]
    depends_on:
      - clone

  - name: upload
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME: ftp
      FTP_PASSWORD: 123456
      PLUGIN_HOSTNAME: 192.168.11.101:21
      PLUGIN_SECURE: false
      PLUGIN_SRC_DIR: /dist  #文件来源，此处是docker容器里build完产生的dist目录
      PLUGIN_DEST_DIR: /fun-app  #传输目地的，此处传输到ftp根目录下的fun文件夹
    when:
      event: [push]
    depends_on:
      - build

volumes:
  - name: cache  # The name use in this pipeline
    host:
      path: /tmp/cache  # 缓存目录挂载到宿主机此路径


trigger:  # 只在以下分支触发
  branch:
    - dev
    - ci
